name: mind spark testing apk
on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: playground
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.0
      path: |
        path/output/bin/
        path/output/test-results
  - name: Upload Logs on Failure
    if: failure()
    uses: actions/upload-artifact@v4
    with:
      name: failure-logs
      path: logs/
